### ISSUE TITLE
no longer works correctly with requires

### ISSUE THREAD

**Issue by devotox** [anvk/google-stocks#5]
you get this
```
{ isObject: [Function: isObject],
  printFuncError: [Function: printFuncError],
  default: [Function: googleStocks] }
```

and error is

```
error: TypeError: googleStocks is not a function
```

**Comment by anvk** [comment]
Look at the `example.js` https://github.com/anvk/google-stocks/blob/master/example.js

I had to add `var googleStocks = require('./dist/google-stocks.js').default;` to make it work. Did not have a chance to fix this one. You can either user as I specified in the example or submit a PR with the fix for this.
